load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "atm",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party:dagger_with_compiler",
    ],
)
