load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "cmd",
    srcs = ["CommandLineAtm.java"],
    main_class = "com.example.atm.cmd.CommandLineAtm",
    deps = ["//src/java/com/example/atm"],
)
